### ISSUE TITLE
better camera angle

### ISSUE THREAD

**Issue by ZeeHatcher** [TheHyperMagi/Shepherd#4]
Third person camera angle that does not get affected by shepherd direction.

**Comment by Zircon332** [comment]
lol i changed the camera, do it again

**Comment by shamilhaqeem** [comment]
Implemented in these commits:
1. 2784905caffc9e1f1af5e901320e849bf1d8f9b9
2. d5ae64c6b55c551d0efa4b8f549ca115be11c7f8

**Comment by shamilhaqeem** [comment]
In my opinion I think we should use the orthogonal projection or one of them instead of using arbitrary angles, but I need to do more research to know how to use the other perspectives provided the camera node.
![image](https://user-images.githubusercontent.com/43197179/103348735-dd867c80-4ad5-11eb-87d7-22bedd837246.png)

**Comment by Zircon332** [comment]
Last two commits made the camera under the world instead of the shepherd, parenting the camera under player makes it harder to rotate, and a single camera is better for cinematics like focusing on multiple things at once and zooming around

**Comment by shamilhaqeem** [comment]
Closing this issue because its a low priority and no straight continuation of discussion can be made for now.
